---
title: "Hi, I'm Medha Khanal"
---

::: {.columns}
::: {.column width="30%"}
images/headshot.jpg{width=100% style="border-radius: 50%;"}
:::

::: {.column width="70%" style="padding-left: 2rem;"}

I'm an International Business and Marketing student at **Cal Poly Pomona** with a strong interest in **business analytics and digital marketing strategy**. I enjoy using technical and creative skills together to understand consumer behaviour and marketing performance.  

:::
:::

---

## About Me

I am currently pursuing my degree in **International Business and Marketing** at Cal Poly Pomona. Through my coursework and hands-on experiences, I’ve developed a foundation in areas such as **digital marketing, data-driven decision-making, international business, trade relations, and ethical + philosophical implications of international business practices**.

---

## 📊 What I Bring

- Experience with **digital marketing campaigns** and social media strategy  
- Understanding of **SEO and online advertising concepts**  
- Ability to analyze data and translate it into actionable insights  
- Strong communication and collaboration skills in team environments
- Strong business management and strategy-related work

---

## Career Interests

I am particularly interested in roles related to:
- Marketing Analytics  
- Digital Marketing  
- Business/Data Analysis  
-International Trade Relations and Laws
-Import + Export Regulations

I am motivated to apply analytical thinking and creative strategy to solve real-world global business challenges.

---

## 📬 Let's Connect

- 📧 Email: ilyakhl313@gmail.com  
- 🔗 https://www.linkedin.com/in/medha-khanal/  
- 💻 https://github.com/ilyakhl313-prog

---

*Welcome to my portfolio.*
