---
title: "Résumé"
---

[View My Resume (PDF)](resume/Resume.pdf){target="_blank"}
---

# Education

| Degree | Year | Institution |
|--------|------|-------------|
| B.S. International Business & Marketing | Present | Cal Poly Pomona |

---

# Experience

### Disney Internship Program, Walt Disney World
*March 2025 - August 2025*
-Participated in Global Team building program
-Hands on experience within garment making/costuming 
-Disney specific workshops in networking and career building excercises

---

### Digital Marketing Trainee, Global Career Accelerator  
*August 2024 – December 2024*  
- Built an **e-commerce website using Shopify**  
- Performed **SEO keyword research** to improve search visibility  
- Created **Google Ads campaigns and social media content** for marketing initiatives  

---

### Fashion PR Intern, CLD PR  
*August 2024 – December 2024*  
- Supported **influencer marketing campaigns and outreach**  
- Conducted **sponsorship research and brand partnerships**  
- Collaborated with a global team on marketing projects  

---

# Skills

- **Marketing:** Digital Marketing, Social Media Campaigns, Branding  
- **Analytics:** SEO Keyword Research, A/B Testing, Campaign Analysis  
- **Tools:** Google Ads, Shopify, Excel, R, Github
- **Class Work Skills** Financial and Managerial Accounting, International exporting + importing law, Business management and strategy, global marketing innitiatives 
- **Languages:** Nepali (Native), English (Fluent), Hindi (Intermediate), French (Intermediate)  

---

# Certifications

- Google Analytics Essential Training – LinkedIn Learning  
- Digital Marketing Foundations – LinkedIn Learning  
- SEO Foundations – LinkedIn Learning  

*Additional certifications available on my LinkedIn profile.*

---

# Summary

With my experienced in cross-cultural collaboration through roles in public relations and the Disney College Program, I was able to work with diverse teams and contribute to event planning, customer engagement, and brand experiences. Demonstrating the ability to analyze market trends, optimize campaign performance, and translate data into actionable insights.

I am very passionate about combining global business perspective with marketing analytics to drive effective strategies and improve business outcomes. 
